/**
 * Writulos GitHub Action — runner script
 *
 * Env vars injected by action.yml:
 *   CHANGED_FILES          comma-separated list of changed file paths
 *   GITHUB_TOKEN           for posting PR comments and committing docs
 *   WRITULOS_ACTION_SECRET optional shared secret header
 *   WRITULOS_API_URL       API endpoint (default: https://writulos.com/api/action-generate)
 *   WRITULOS_OUTPUT_DIR    output directory (default: docs)
 *   PR_NUMBER              set by GitHub on pull_request events
 *   EVENT_NAME             github.event_name
 *   REPO_NAME              github.repository (owner/repo)
 */
import fs from 'fs';
import path from 'path';

const API_URL = process.env.WRITULOS_API_URL ?? 'https://writulos.com/api/action-generate';
const OUTPUT_DIR = process.env.WRITULOS_OUTPUT_DIR ?? 'docs';
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const WRITULOS_SECRET = process.env.WRITULOS_ACTION_SECRET ?? '';
const PR_NUMBER = process.env.PR_NUMBER;
const EVENT_NAME = process.env.EVENT_NAME;
const REPO_NAME = process.env.REPO_NAME;

// Parse comma-separated changed files from env
const changedFiles = (process.env.CHANGED_FILES || '')
  .split(',')
  .map((f) => f.trim())
  .filter(Boolean);

if (changedFiles.length === 0) {
  console.log('Writulos: no changed code files detected. Skipping.');
  process.exit(0);
}

console.log(`\nWritulos — generating docs for ${changedFiles.length} file(s):`);
changedFiles.forEach((f) => console.log(`  • ${f}`));

async function generateDoc(filePath) {
  let code;
  try {
    code = fs.readFileSync(filePath, 'utf8');
  } catch {
    console.warn(`  [skip] Could not read ${filePath}`);
    return null;
  }

  if (!code.trim()) {
    console.warn(`  [skip] ${filePath} is empty`);
    return null;
  }

  if (code.length > 100_000) {
    console.warn(`  [skip] ${filePath} is over 100KB`);
    return null;
  }

  const headers = { 'Content-Type': 'application/json' };
  if (WRITULOS_SECRET) headers['x-writulos-secret'] = WRITULOS_SECRET;

  const response = await fetch(API_URL, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      code,
      filename: filePath,
      context: `File from GitHub repository: ${REPO_NAME}`,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    console.error(`  [error] ${filePath}: HTTP ${response.status} — ${err}`);
    return null;
  }

  const data = await response.json();
  return data.documentation ?? null;
}

function writeDoc(filePath, documentation) {
  // Mirror source path inside OUTPUT_DIR
  // e.g.  src/utils/auth.ts  →  docs/src/utils/auth.md
  const docPath = path.join(OUTPUT_DIR, filePath.replace(/\.[^.]+$/, '.md'));
  fs.mkdirSync(path.dirname(docPath), { recursive: true });
  fs.writeFileSync(docPath, documentation, 'utf8');
  console.log(`  [done] → ${docPath}`);
  return docPath;
}

async function postPRComment(summaryLines) {
  if (!GITHUB_TOKEN || !PR_NUMBER || EVENT_NAME !== 'pull_request') return;

  const fileList = summaryLines.map((l) => `- \`${l}\``).join('\n');
  const body = [
    '## 📝 Writulos — Documentation Generated',
    '',
    'Documentation was auto-generated for the following changed files:',
    '',
    fileList,
    '',
    '> Docs are committed to the `' + OUTPUT_DIR + '/` folder in this branch.',
    '',
    '_Generated by [Writulos](https://writulos.com) — paste code, get docs._',
  ].join('\n');

  const [owner, repo] = REPO_NAME.split('/');
  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/issues/${PR_NUMBER}/comments`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github+json',
      },
      body: JSON.stringify({ body }),
    }
  );

  if (res.ok) {
    console.log('\nPR comment posted successfully.');
  } else {
    console.warn('Failed to post PR comment:', await res.text());
  }
}

async function main() {
  const written = [];

  for (const filePath of changedFiles) {
    console.log(`\nProcessing: ${filePath}`);
    const documentation = await generateDoc(filePath);
    if (documentation) {
      const docPath = writeDoc(filePath, documentation);
      written.push(docPath);
    }
  }

  if (written.length === 0) {
    console.log('\nWritulos: no docs generated.');
    return;
  }

  console.log(`\nWritulos: done. Generated ${written.length} doc(s).`);
  await postPRComment(written);
}

main().catch((err) => {
  console.error('Writulos action failed:', err);
  process.exit(1);
});
